services:
  - type: web
    name: audiotoolkit
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
